const app=document.getElementById("app"),names=["💙💛 JCI Lekki Royale Trivia","🧠 JCI Knowledge","😂 Emoji Guess","🇳🇬 Nigerian Fun","⚡ 10-Second Challenge"],keys=["round1","round2","round3","round4","round5"];
let s={name:"",r:0,i:0,sc:[0,0,0,0,0],timer:null};
const esc=x=>String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const total=()=>s.sc.reduce((a,b)=>a+b,0);
function home(){app.innerHTML=`<main class="shell center"><div class="badge">💙💛 JCI LEKKI ROYALE</div><h1>KIT Games Night 2026</h1><p>Keep In Touch • Play • Connect • Compete</p><div class="card"><label>Your name / nickname</label><input id="name" maxlength="50" placeholder="Enter your name"><button class="primary" onclick="start()">Start Game 🎮</button></div><small>50 questions • 500 points</small></main>`}
function start(){let n=document.getElementById("name").value.trim();if(!n)return alert("Please enter your name.");s.name=n;s.r=0;s.i=0;s.sc=[0,0,0,0,0];intro()}
function intro(){app.innerHTML=`<main class="shell center"><div class="roundNo">ROUND ${s.r+1} OF 5</div><h1>${names[s.r]}</h1><p>10 questions • 10 points each</p><button class="primary" onclick="q()">Let's Go 🚀</button></main>`}
function q(){clearInterval(s.timer);let d=QUESTIONS[keys[s.r]],x=d[s.i];if(!x){if(s.r<4){s.r++;s.i=0;intro()}else result();return}if(s.r===4){s.t=10;app.innerHTML=`<main class="shell game"><div class="top"><span>ROUND 5/5</span><b>${s.sc[4]}/100</b></div><div class="timer" id="tm">10</div><div class="card"><div>QUESTION ${s.i+1}/10</div><h2>${esc(x[0])}</h2><input id="ans" placeholder="Separate answers with commas"><button class="primary" onclick="speed()">Submit</button><small>Enter 5 valid answers.</small></div></main>`;s.timer=setInterval(()=>{s.t--;document.getElementById("tm").textContent=s.t;if(s.t<=0)speed(true)},1000)}else{app.innerHTML=`<main class="shell game"><div class="top"><span>ROUND ${s.r+1}/5</span><b>${s.sc[s.r]}/100</b></div><div class="progress"><i style="width:${s.i*10}%"></i></div><div class="card"><div>QUESTION ${s.i+1}/10</div><h2>${esc(x[0])}</h2><div class="options">${x[1].map((v,i)=>`<button onclick="ans(${i})">${String.fromCharCode(65+i)}. ${esc(v)}</button>`).join("")}</div></div></main>`}}
function ans(i){clearInterval(s.timer);if(i===QUESTIONS[keys[s.r]][s.i][2])s.sc[s.r]+=10;s.i++;q()}
function norm(x){return x.toLowerCase().replace(/[^\p{L}\p{N}\s]/gu," ").replace(/\s+/g," ").trim()}
function speed(timeout=false){if(!document.getElementById("ans"))return;clearInterval(s.timer);let x=QUESTIONS.round5[s.i],a=document.getElementById("ans").value.split(",").map(norm).filter(Boolean),u=[...new Set(a.filter(v=>x[1].map(norm).includes(v)))];if(u.length>=5&&!timeout)s.sc[4]+=10;s.i++;q()}
async function result(){let t=total();try{await fetch("/api/submit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name:s.name,scores:{round1:s.sc[0],round2:s.sc[1],round3:s.sc[2],round4:s.sc[3],round5:s.sc[4]}})})}catch(e){}let m=encodeURIComponent(`🎮 KIT GAMES NIGHT 2026\n💙💛 JCI Lekki Royale\n\nI scored ${t}/500! 🔥🏆\n\nCan you beat my score? 😎\n#KITGamesNight #JCILekkiRoyale`);app.innerHTML=`<main class="shell center"><div class="badge">GAME COMPLETE 🎉</div><h1>${esc(s.name)}</h1><div class="scorecard"><div class="big">${t}<small>/500</small></div>${s.sc.map((x,i)=>`<div class="line"><span>Round ${i+1}</span><b>${x}/100</b></div>`).join("")}</div><a class="primary" target="_blank" href="https://wa.me/?text=${m}">📲 Share My Score</a><button class="secondary" onclick="home()">Play Again</button></main>`}
home();