const QUESTIONS={
round1:[
["What does KIT stand for?",["Keep In Touch","Keep It Together","Know It Today","Keep Inspiring Together"],0],
["Which organization is hosting the KIT Games Night?",["JCI Lagos","JCI Lekki Royale","JCI Nigeria","JCI Africa"],1],
["What is the primary purpose of KIT?",["Fundraising","Competition","Keeping members connected","Leadership elections"],2],
["What platform is being used for the KIT Games Night interaction?",["Telegram","Instagram","WhatsApp","Zoom"],2],
["KIT is primarily designed to promote:",["Competition","Connection and bonding","Fundraising","Recruitment only"],1],
["Which of these best describes a JCI member?",["Passive observer","Active young leader","Political office holder","Business owner only"],1],
["What does JCI stand for?",["Junior Citizens International","Junior Chamber International","Young Leaders International","Junior Community Initiative"],1],
["JCI focuses on developing young people through:",["Leadership and active citizenship","Entertainment only","Sports only","Academic examinations"],0],
["Which is most important during KIT?",["Winning at all costs","Being the fastest","Connecting with fellow members","Staying silent"],2],
["Which colour combination is associated with JCI Lekki Royale?",["Red and white","Green and yellow","Blue and yellow","Black and gold"],2]],
round2:[
["JCI is a global network of young people.",["True","False"],0],
["JCI encourages members to create positive change in their communities.",["True","False"],0],
["Which of these is NOT typically associated with JCI?",["Leadership development","Community impact","Active citizenship","Professional development","Professional football league"],4],
["A JCI member is often referred to as a:",["Jaycee","Junior","J-Citizen","Chamberite"],0],
["Which of these is a major benefit of participating actively in JCI?",["Leadership experience","Guaranteed employment","Automatic political appointment","Free international travel"],0],
["What is one of the main purposes of JCI?",["To promote active citizenship and leadership","To organize sporting competitions","To provide political appointments","To operate as a business company"],0],
["JCI members are encouraged to:",["Wait for others to solve community problems","Take initiative and create positive change","Focus only on personal success","Avoid leadership responsibilities"],1],
["Which of these is an example of active citizenship?",["Ignoring community problems","Organizing a community development project","Refusing to volunteer","Avoiding teamwork"],1],
["Which skill can a JCI member develop through participating in projects?",["Leadership","Communication","Teamwork","All of the above"],3],
["JCI provides opportunities for members to connect with:",["Only members in their local chapter","Young people locally and internationally","Only people in their profession","Only elected government officials"],1]],
round3:[
["🦁👑",["The Lion King","Black Panther","The Jungle Book","The Lion Guard"],0],
["🧙‍♂️⚡👓",["Harry Potter","The Hobbit","Percy Jackson","Fantastic Beasts"],0],
["🚢🧊💔",["Titanic","Moana","Avatar","The Notebook"],0],
["🐟🔎🌊",["Finding Nemo","Shark Tale","The Little Mermaid","Aquaman"],0],
["👻🚫",["Ghostbusters","Beetlejuice","Casper","The Conjuring"],0],
["👠🎃👸",["Cinderella","Frozen","Enchanted","Snow White"],0],
["🕷️🧑",["Spider-Man","Batman","Ant-Man","Superman"],0],
["🦖🏞️",["Jurassic Park","King Kong","Godzilla","The Lost World"],0],
["🧊❄️👸",["Frozen","Ice Age","Brave","Snow Queen"],0],
["🦍🏙️",["King Kong","Godzilla","Rampage","Planet of the Apes"],0]],
round4:[
["What is Nigeria's capital city?",["Lagos","Abuja","Kano","Ibadan"],1],
["Which Nigerian city is known as the 'Centre of Excellence'?",["Abuja","Port Harcourt","Lagos","Enugu"],2],
["Which of these is a Nigerian staple food?",["Jollof rice","Sushi","Tacos","Pasta"],0],
["Which Nigerian language is widely spoken in southwestern Nigeria?",["Yoruba","Hausa","Igbo","Tiv"],0],
["Which of these is a popular Nigerian party food?",["Jollof rice","Croissant","Sushi","Lasagna"],0],
["What does 'Abeg' commonly mean in Nigerian Pidgin?",["Please","Come here","Leave","Quickly"],0],
["'How far?' in Nigerian Pidgin is commonly used to mean:",["How far is the journey?","How are you?/What's up?","Where are you going?","How much?"],1],
["Which of these is NOT a Nigerian state?",["Lagos","Kaduna","Abuja","Enugu"],2],
["Which Nigerian city is popularly known as the 'Coal City'?",["Enugu","Kano","Ibadan","Lagos"],0],
["Which of these is a popular Nigerian street food?",["Akara","Sushi","Croissant","Tacos"],0]],
round5:[
["Name 5 Nigerian foods.",["jollof rice","fried rice","pounded yam","egusi soup","eba","amala","semo","ofada rice","akara","moi moi","pepper soup","suya","yam","beans","plantain","tuwo","okro soup","efo riro","afang soup","banga soup"],5],
["Name 5 Nigerian states.",["lagos","ogun","oyo","osun","ondo","ekiti","edo","delta","rivers","bayelsa","anambra","imo","enugu","abia","ebonyi","cross river","akwa ibom","benue","kogi","kwara","niger","kaduna","kano","katsina","kebbi","sokoto","zamfara","jigawa","bauchi","borno","yobe","adamawa","taraba","plateau","nasarawa","gombe"],5],
["Name 5 countries beginning with S.",["spain","sweden","switzerland","senegal","singapore","somalia","sudan","south africa","south sudan","serbia","slovakia","slovenia","sri lanka","syria","suriname","samoa","seychelles","sierra leone","solomon islands","saudi arabia"],5],
["Name 5 things you can find in a handbag.",["phone","wallet","purse","keys","lipstick","makeup","mirror","pen","notebook","tissue","hand sanitizer","perfume","comb","charger","power bank","cash","id card","earphones"],5],
["Name 5 JCI-related words.",["jci","leadership","community","impact","volunteer","active citizenship","project","member","chapter","network","training","development","service","partnership","president","directorate"],5],
["Name 5 colours.",["red","blue","yellow","green","orange","purple","pink","black","white","brown","grey","gray","gold","silver"],5],
["Name 5 things people do at parties.",["dance","eat","drink","sing","take pictures","talk","laugh","play games","socialize","greet","network","celebrate"],5],
["Name 5 professions.",["doctor","teacher","lawyer","engineer","nurse","accountant","architect","journalist","farmer","pilot","dentist","pharmacist","designer","writer","chef","developer","consultant"],5],
["Name 5 social media platforms.",["facebook","instagram","tiktok","youtube","x","twitter","linkedin","snapchat","whatsapp","telegram","threads","pinterest"],5],
["Name 5 things you can find in a kitchen.",["pot","pan","plate","spoon","fork","knife","cup","blender","kettle","stove","oven","fridge","refrigerator","sink","microwave","bowl","tray","cutting board"],5]]
};